[target.x86_64-pc-windows-gnu]
linker = "C:/msys64/mingw64/bin/gcc.exe"
ar = "C:/msys64/mingw64/bin/ar.exe"
rustflags = [
    "-L", "C:/msys64/mingw64/lib",
    "-L", "C:/msys64/mingw64/x86_64-w64-mingw32/lib",
]
